version: '2.2'

services:

  

  timesheet:
  
    image: raedjarboui/timesheet
    build: ./
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myapp-mysql:3306/timesheet?autoReconnect=true&useSSL=false

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timesheet
    ports:
      - 3307:3306    